<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class RailRampSeeder extends Seeder
{
    /**
     * Seed the rail_ramps table with real US intermodal terminal data.
     *
     * Run with: php artisan db:seed --class=RailRampSeeder
     */
    public function run(): void
    {
        $now = now();

        $ramps = [
            // ----------------------------------------------------------------
            // BNSF Railway
            // ----------------------------------------------------------------
            [
                'name'         => 'BNSF Los Angeles Hobart Intermodal Facility',
                'code'         => 'LAXH',
                'carrier_scac' => 'BNSF',
                'city'         => 'Los Angeles',
                'state'        => 'CA',
                'latitude'     => 33.9889,
                'longitude'    => -118.2365,
                'address'      => '3401 E Washington Blvd, Los Angeles, CA 90023',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'BNSF Chicago Logistics Park',
                'code'         => 'CHILP',
                'carrier_scac' => 'BNSF',
                'city'         => 'Elwood',
                'state'        => 'IL',
                'latitude'     => 41.3951,
                'longitude'    => -88.0739,
                'address'      => '26900 W Intermodal Dr, Elwood, IL 60421',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'BNSF Kansas City Intermodal Facility',
                'code'         => 'MKCK',
                'carrier_scac' => 'BNSF',
                'city'         => 'Kansas City',
                'state'        => 'KS',
                'latitude'     => 39.1105,
                'longitude'    => -94.6277,
                'address'      => '7400 Speaker Rd, Kansas City, KS 66111',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'BNSF Memphis Intermodal Facility',
                'code'         => 'MEMB',
                'carrier_scac' => 'BNSF',
                'city'         => 'Memphis',
                'state'        => 'TN',
                'latitude'     => 35.1045,
                'longitude'    => -90.1144,
                'address'      => '3801 Tchulahoma Rd, Memphis, TN 38118',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'BNSF Dallas Alliance Intermodal Facility',
                'code'         => 'DFWA',
                'carrier_scac' => 'BNSF',
                'city'         => 'Fort Worth',
                'state'        => 'TX',
                'latitude'     => 32.9879,
                'longitude'    => -97.3308,
                'address'      => '3100 Alliance Gateway Fwy, Fort Worth, TX 76177',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'BNSF Seattle Intermodal Facility',
                'code'         => 'SEAB',
                'carrier_scac' => 'BNSF',
                'city'         => 'Seattle',
                'state'        => 'WA',
                'latitude'     => 47.5880,
                'longitude'    => -122.3290,
                'address'      => '2250 E Marginal Way S, Seattle, WA 98134',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'BNSF Denver Intermodal Facility',
                'code'         => 'DENB',
                'carrier_scac' => 'BNSF',
                'city'         => 'Denver',
                'state'        => 'CO',
                'latitude'     => 39.7614,
                'longitude'    => -104.9695,
                'address'      => '6500 N Broadway, Denver, CO 80221',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'BNSF Phoenix Intermodal Facility',
                'code'         => 'PHXB',
                'carrier_scac' => 'BNSF',
                'city'         => 'Phoenix',
                'state'        => 'AZ',
                'latitude'     => 33.4151,
                'longitude'    => -112.0985,
                'address'      => '4747 S 43rd Ave, Phoenix, AZ 85041',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'BNSF Houston Intermodal Facility',
                'code'         => 'HOUB',
                'carrier_scac' => 'BNSF',
                'city'         => 'Houston',
                'state'        => 'TX',
                'latitude'     => 29.7355,
                'longitude'    => -95.2672,
                'address'      => '9201 Railwood Dr, Houston, TX 77078',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'BNSF San Bernardino Intermodal Facility',
                'code'         => 'SANB',
                'carrier_scac' => 'BNSF',
                'city'         => 'San Bernardino',
                'state'        => 'CA',
                'latitude'     => 34.0924,
                'longitude'    => -117.2869,
                'address'      => '399 S Waterman Ave, San Bernardino, CA 92408',
                'ramp_type'    => 'intermodal',
            ],

            // ----------------------------------------------------------------
            // Union Pacific Railroad
            // ----------------------------------------------------------------
            [
                'name'         => 'UP Los Angeles ICTF Intermodal Container Transfer Facility',
                'code'         => 'LAXI',
                'carrier_scac' => 'UP',
                'city'         => 'Long Beach',
                'state'        => 'CA',
                'latitude'     => 33.8121,
                'longitude'    => -118.2097,
                'address'      => '584 W Harry Bridges Blvd, Wilmington, CA 90744',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'UP Chicago Global III Intermodal Facility',
                'code'         => 'CHIG3',
                'carrier_scac' => 'UP',
                'city'         => 'Joliet',
                'state'        => 'IL',
                'latitude'     => 41.5250,
                'longitude'    => -88.1000,
                'address'      => '3400 S Houbolt Rd, Joliet, IL 60431',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'UP Dallas Intermodal Terminal',
                'code'         => 'DFWU',
                'carrier_scac' => 'UP',
                'city'         => 'Dallas',
                'state'        => 'TX',
                'latitude'     => 32.8124,
                'longitude'    => -96.9103,
                'address'      => '2727 N Stemmons Fwy, Dallas, TX 75207',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'UP Houston Englewood Intermodal Facility',
                'code'         => 'HOUU',
                'carrier_scac' => 'UP',
                'city'         => 'Houston',
                'state'        => 'TX',
                'latitude'     => 29.7505,
                'longitude'    => -95.3097,
                'address'      => '4300 Lathrop St, Houston, TX 77020',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'UP San Antonio Intermodal Facility',
                'code'         => 'SAIU',
                'carrier_scac' => 'UP',
                'city'         => 'San Antonio',
                'state'        => 'TX',
                'latitude'     => 29.4241,
                'longitude'    => -98.4936,
                'address'      => '7000 W Commerce St, San Antonio, TX 78237',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'UP Memphis Intermodal Facility',
                'code'         => 'MEMU',
                'carrier_scac' => 'UP',
                'city'         => 'Memphis',
                'state'        => 'TN',
                'latitude'     => 35.0734,
                'longitude'    => -90.0235,
                'address'      => '2600 Lamar Ave, Memphis, TN 38114',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'UP Atlanta Intermodal Facility',
                'code'         => 'ATLU',
                'carrier_scac' => 'UP',
                'city'         => 'Atlanta',
                'state'        => 'GA',
                'latitude'     => 33.7490,
                'longitude'    => -84.3880,
                'address'      => '590 McDonough Blvd SE, Atlanta, GA 30315',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'UP Jacksonville Intermodal Facility',
                'code'         => 'JACU',
                'carrier_scac' => 'UP',
                'city'         => 'Jacksonville',
                'state'        => 'FL',
                'latitude'     => 30.3322,
                'longitude'    => -81.6557,
                'address'      => '5560 Commonwealth Ave, Jacksonville, FL 32254',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'UP Savannah Intermodal Facility',
                'code'         => 'SAVU',
                'carrier_scac' => 'UP',
                'city'         => 'Savannah',
                'state'        => 'GA',
                'latitude'     => 32.0835,
                'longitude'    => -81.0998,
                'address'      => '100 Crossgate Rd, Garden City, GA 31408',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'UP New Orleans Intermodal Facility',
                'code'         => 'MSYU',
                'carrier_scac' => 'UP',
                'city'         => 'New Orleans',
                'state'        => 'LA',
                'latitude'     => 29.9511,
                'longitude'    => -90.0715,
                'address'      => '4000 Jourdan Rd, New Orleans, LA 70126',
                'ramp_type'    => 'intermodal',
            ],

            // ----------------------------------------------------------------
            // CSX Transportation
            // ----------------------------------------------------------------
            [
                'name'         => 'CSX Jacksonville Intermodal Terminal',
                'code'         => 'JACX',
                'carrier_scac' => 'CSX',
                'city'         => 'Jacksonville',
                'state'        => 'FL',
                'latitude'     => 30.3688,
                'longitude'    => -81.6602,
                'address'      => '1440 Talleyrand Ave, Jacksonville, FL 32206',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'CSX Savannah Intermodal Terminal',
                'code'         => 'SAVX',
                'carrier_scac' => 'CSX',
                'city'         => 'Savannah',
                'state'        => 'GA',
                'latitude'     => 32.1373,
                'longitude'    => -81.2290,
                'address'      => '2 Garden City Terminal Rd, Garden City, GA 31408',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'CSX Atlanta Fairburn Intermodal Facility',
                'code'         => 'ATFX',
                'carrier_scac' => 'CSX',
                'city'         => 'Fairburn',
                'state'        => 'GA',
                'latitude'     => 33.5673,
                'longitude'    => -84.5788,
                'address'      => '7777 Lester Rd, Fairburn, GA 30213',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'CSX Charlotte Intermodal Terminal',
                'code'         => 'CLTX',
                'carrier_scac' => 'CSX',
                'city'         => 'Charlotte',
                'state'        => 'NC',
                'latitude'     => 35.2271,
                'longitude'    => -80.8431,
                'address'      => '4601 Chesapeake Dr, Charlotte, NC 28216',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'CSX Nashville Radnor Intermodal Facility',
                'code'         => 'BNAX',
                'carrier_scac' => 'CSX',
                'city'         => 'Nashville',
                'state'        => 'TN',
                'latitude'     => 36.0956,
                'longitude'    => -86.7475,
                'address'      => '2000 Radnor St, Nashville, TN 37211',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'CSX Chicago 59th Street Intermodal Terminal',
                'code'         => 'CHI59',
                'carrier_scac' => 'CSX',
                'city'         => 'Chicago',
                'state'        => 'IL',
                'latitude'     => 41.7874,
                'longitude'    => -87.6249,
                'address'      => '5900 S Wolcott Ave, Chicago, IL 60636',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'CSX Baltimore Intermodal Facility',
                'code'         => 'BLTX',
                'carrier_scac' => 'CSX',
                'city'         => 'Baltimore',
                'state'        => 'MD',
                'latitude'     => 39.2904,
                'longitude'    => -76.6122,
                'address'      => '3601 Broening Hwy, Baltimore, MD 21224',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'CSX Miami Hialeah Intermodal Terminal',
                'code'         => 'MIAX',
                'carrier_scac' => 'CSX',
                'city'         => 'Hialeah',
                'state'        => 'FL',
                'latitude'     => 25.8576,
                'longitude'    => -80.2781,
                'address'      => '7301 NW 37th Ave, Miami, FL 33147',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'CSX Tampa Intermodal Terminal',
                'code'         => 'TMPX',
                'carrier_scac' => 'CSX',
                'city'         => 'Tampa',
                'state'        => 'FL',
                'latitude'     => 27.9506,
                'longitude'    => -82.4572,
                'address'      => '801 Twiggs St, Tampa, FL 33602',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'CSX Philadelphia Intermodal Terminal',
                'code'         => 'PHIX',
                'carrier_scac' => 'CSX',
                'city'         => 'Philadelphia',
                'state'        => 'PA',
                'latitude'     => 39.9526,
                'longitude'    => -75.1652,
                'address'      => '3001 S 61st St, Philadelphia, PA 19153',
                'ramp_type'    => 'intermodal',
            ],

            // ----------------------------------------------------------------
            // Norfolk Southern Railway
            // ----------------------------------------------------------------
            [
                'name'         => 'NS Atlanta Austell Intermodal Terminal',
                'code'         => 'ATNS',
                'carrier_scac' => 'NS',
                'city'         => 'Austell',
                'state'        => 'GA',
                'latitude'     => 33.8131,
                'longitude'    => -84.6335,
                'address'      => '2710 Austell Rd, Marietta, GA 30008',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'NS Charlotte Intermodal Terminal',
                'code'         => 'CLNS',
                'carrier_scac' => 'NS',
                'city'         => 'Charlotte',
                'state'        => 'NC',
                'latitude'     => 35.2033,
                'longitude'    => -80.9801,
                'address'      => '3500 Rozzelles Ferry Rd, Charlotte, NC 28208',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'NS Chicago Landers Intermodal Terminal',
                'code'         => 'CHNS',
                'carrier_scac' => 'NS',
                'city'         => 'Chicago',
                'state'        => 'IL',
                'latitude'     => 41.7251,
                'longitude'    => -87.6655,
                'address'      => '7600 S Vincennes Ave, Chicago, IL 60620',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'NS Columbus Intermodal Terminal',
                'code'         => 'COLNS',
                'carrier_scac' => 'NS',
                'city'         => 'Columbus',
                'state'        => 'OH',
                'latitude'     => 39.9612,
                'longitude'    => -82.9988,
                'address'      => '2275 Rohr Rd, Groveport, OH 43125',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'NS Detroit Livernois Intermodal Terminal',
                'code'         => 'DTNS',
                'carrier_scac' => 'NS',
                'city'         => 'Detroit',
                'state'        => 'MI',
                'latitude'     => 42.2814,
                'longitude'    => -83.2097,
                'address'      => '12800 Livernois Ave, Detroit, MI 48204',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'NS Harrisburg Intermodal Terminal',
                'code'         => 'HBGNS',
                'carrier_scac' => 'NS',
                'city'         => 'Harrisburg',
                'state'        => 'PA',
                'latitude'     => 40.2732,
                'longitude'    => -76.8867,
                'address'      => '1800 Paxton St, Harrisburg, PA 17104',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'NS Jacksonville Intermodal Terminal',
                'code'         => 'JACNS',
                'carrier_scac' => 'NS',
                'city'         => 'Jacksonville',
                'state'        => 'FL',
                'latitude'     => 30.3494,
                'longitude'    => -81.7335,
                'address'      => '5200 W Beaver St, Jacksonville, FL 32254',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'NS Memphis Intermodal Terminal',
                'code'         => 'MEMNS',
                'carrier_scac' => 'NS',
                'city'         => 'Memphis',
                'state'        => 'TN',
                'latitude'     => 35.1309,
                'longitude'    => -90.0477,
                'address'      => '2650 Non Connah Rd, Memphis, TN 38132',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'NS New Orleans Intermodal Terminal',
                'code'         => 'MSNS',
                'carrier_scac' => 'NS',
                'city'         => 'New Orleans',
                'state'        => 'LA',
                'latitude'     => 29.9500,
                'longitude'    => -90.0630,
                'address'      => '3700 River Rd, New Orleans, LA 70121',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'NS Norfolk Intermodal Terminal',
                'code'         => 'ORFNS',
                'carrier_scac' => 'NS',
                'city'         => 'Norfolk',
                'state'        => 'VA',
                'latitude'     => 36.8485,
                'longitude'    => -76.2921,
                'address'      => '1 Berkley Ave, Norfolk, VA 23523',
                'ramp_type'    => 'intermodal',
            ],

            // ----------------------------------------------------------------
            // Canadian National Railway (CN)
            // ----------------------------------------------------------------
            [
                'name'         => 'CN Chicago Logistics Park',
                'code'         => 'CHICN',
                'carrier_scac' => 'CN',
                'city'         => 'Harvey',
                'state'        => 'IL',
                'latitude'     => 41.6100,
                'longitude'    => -87.6467,
                'address'      => '16101 S Halsted St, Harvey, IL 60426',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'CN Detroit Intermodal Terminal',
                'code'         => 'DTCN',
                'carrier_scac' => 'CN',
                'city'         => 'Detroit',
                'state'        => 'MI',
                'latitude'     => 42.3223,
                'longitude'    => -83.0458,
                'address'      => '2300 Michigan Ave, Detroit, MI 48216',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'CN Memphis Intermodal Facility',
                'code'         => 'MEMCN',
                'carrier_scac' => 'CN',
                'city'         => 'Memphis',
                'state'        => 'TN',
                'latitude'     => 35.1450,
                'longitude'    => -90.0521,
                'address'      => '4747 Horn Lake Rd, Memphis, TN 38109',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'CN Mobile Intermodal Terminal',
                'code'         => 'MOBCN',
                'carrier_scac' => 'CN',
                'city'         => 'Mobile',
                'state'        => 'AL',
                'latitude'     => 30.6954,
                'longitude'    => -88.0399,
                'address'      => '1 Cochrane Bridge Rd, Mobile, AL 36602',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'CN New Orleans Intermodal Facility',
                'code'         => 'MSYCN',
                'carrier_scac' => 'CN',
                'city'         => 'New Orleans',
                'state'        => 'LA',
                'latitude'     => 29.9411,
                'longitude'    => -90.0855,
                'address'      => '1 Robin St, New Orleans, LA 70130',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'CN Jackson Intermodal Facility',
                'code'         => 'JACKCN',
                'carrier_scac' => 'CN',
                'city'         => 'Jackson',
                'state'        => 'MS',
                'latitude'     => 32.2988,
                'longitude'    => -90.1848,
                'address'      => '300 W Capitol St, Jackson, MS 39203',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'CN Joliet Intermodal Facility',
                'code'         => 'JOLICN',
                'carrier_scac' => 'CN',
                'city'         => 'Joliet',
                'state'        => 'IL',
                'latitude'     => 41.5250,
                'longitude'    => -88.0817,
                'address'      => '2800 S Houbolt Rd, Joliet, IL 60431',
                'ramp_type'    => 'intermodal',
            ],

            // ----------------------------------------------------------------
            // Canadian Pacific Kansas City (CPKC / CP)
            // ----------------------------------------------------------------
            [
                'name'         => 'CPKC Kansas City Intermodal Facility',
                'code'         => 'MKCCP',
                'carrier_scac' => 'CP',
                'city'         => 'Kansas City',
                'state'        => 'MO',
                'latitude'     => 39.0997,
                'longitude'    => -94.5786,
                'address'      => '2400 Madison Ave, Kansas City, MO 64108',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'CPKC Chicago Bensenville Intermodal Facility',
                'code'         => 'CHICP',
                'carrier_scac' => 'CP',
                'city'         => 'Bensenville',
                'state'        => 'IL',
                'latitude'     => 41.9581,
                'longitude'    => -87.9403,
                'address'      => '200 W Wood St, Bensenville, IL 60106',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'CPKC Laredo Intermodal Facility',
                'code'         => 'LRDCP',
                'carrier_scac' => 'CP',
                'city'         => 'Laredo',
                'state'        => 'TX',
                'latitude'     => 27.5036,
                'longitude'    => -99.5075,
                'address'      => '1 Zaragoza St, Laredo, TX 78040',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'CPKC Houston Intermodal Facility',
                'code'         => 'HOUCP',
                'carrier_scac' => 'CP',
                'city'         => 'Houston',
                'state'        => 'TX',
                'latitude'     => 29.7890,
                'longitude'    => -95.3677,
                'address'      => '7800 Jensen Dr, Houston, TX 77093',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'CPKC Dallas Intermodal Facility',
                'code'         => 'DFWCP',
                'carrier_scac' => 'CP',
                'city'         => 'Dallas',
                'state'        => 'TX',
                'latitude'     => 32.7767,
                'longitude'    => -96.7970,
                'address'      => '4400 S Cockrell Hill Rd, Dallas, TX 75236',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'CPKC Detroit Intermodal Facility',
                'code'         => 'DTCP',
                'carrier_scac' => 'CP',
                'city'         => 'Detroit',
                'state'        => 'MI',
                'latitude'     => 42.3830,
                'longitude'    => -83.1020,
                'address'      => '100 Detroit Terminal Blvd, Detroit, MI 48209',
                'ramp_type'    => 'intermodal',
            ],

            // ----------------------------------------------------------------
            // Kansas City Southern (KCS)
            // ----------------------------------------------------------------
            [
                'name'         => 'KCS Laredo Intermodal Ramp',
                'code'         => 'LRDKC',
                'carrier_scac' => 'KCS',
                'city'         => 'Laredo',
                'state'        => 'TX',
                'latitude'     => 27.5060,
                'longitude'    => -99.4921,
                'address'      => '100 Bridge St, Laredo, TX 78040',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'KCS Kansas City Intermodal Facility',
                'code'         => 'MKCKC',
                'carrier_scac' => 'KCS',
                'city'         => 'Kansas City',
                'state'        => 'MO',
                'latitude'     => 39.1142,
                'longitude'    => -94.6275,
                'address'      => '427 W 12th St, Kansas City, MO 64105',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'KCS Shreveport Intermodal Facility',
                'code'         => 'SHRK',
                'carrier_scac' => 'KCS',
                'city'         => 'Shreveport',
                'state'        => 'LA',
                'latitude'     => 32.5252,
                'longitude'    => -93.7502,
                'address'      => '100 Texas Ave, Shreveport, LA 71101',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'KCS Dallas Wylie Intermodal Ramp',
                'code'         => 'DFWKC',
                'carrier_scac' => 'KCS',
                'city'         => 'Wylie',
                'state'        => 'TX',
                'latitude'     => 33.0151,
                'longitude'    => -96.5388,
                'address'      => '2600 N Hwy 78, Wylie, TX 75098',
                'ramp_type'    => 'intermodal',
            ],
            [
                'name'         => 'KCS Houston Intermodal Facility',
                'code'         => 'HOUKC',
                'carrier_scac' => 'KCS',
                'city'         => 'Houston',
                'state'        => 'TX',
                'latitude'     => 29.7604,
                'longitude'    => -95.3698,
                'address'      => '3800 Navigation Blvd, Houston, TX 77003',
                'ramp_type'    => 'intermodal',
            ],
        ];

        foreach ($ramps as $ramp) {
            DB::table('rail_ramps')->upsert(
                array_merge($ramp, [
                    'id'         => Str::uuid()->toString(),
                    'is_active'  => true,
                    'metadata'   => null,
                    'created_at' => $now,
                    'updated_at' => $now,
                ]),
                ['code'],
                ['name', 'carrier_scac', 'city', 'state', 'latitude', 'longitude', 'address', 'ramp_type', 'is_active', 'updated_at']
            );
        }

        $this->command->info('RailRampSeeder: ' . count($ramps) . ' ramps seeded.');
    }
}
