<?php

namespace App\Http\Controllers\Api\V1\Vessel;

use App\Http\Controllers\Controller;
use App\Http\Requests\Vessel\UpdateVesselRequest;
use App\Http\Resources\Container\ContainerResource;
use App\Http\Resources\Vessel\VesselResource;
use App\Models\Tenant\Vessel;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class VesselController extends Controller
{
    /**
     * GET /api/v1/vessels
     */
    public function index(Request $request): JsonResponse
    {
        $query = Vessel::query();

        if ($request->has('filters')) {
            $this->applyFilters($query, $request->input('filters', []));
        }

        $this->applySorting(
            $query,
            $request->input('order_by', 'eta'),
            (int) $request->input('direction', 1)
        );

        return $this->paginateResource($query, $request, VesselResource::class);
    }

    /**
     * GET /api/v1/vessels/{uuid}
     */
    public function show(string $uuid): JsonResponse
    {
        $vessel = Vessel::where('uuid', $uuid)->first();

        if (! $vessel) {
            return $this->notFound('Vessel not found');
        }

        return $this->success(new VesselResource($vessel));
    }

    /**
     * PUT /api/v1/vessels/{uuid}
     */
    public function update(UpdateVesselRequest $request, string $uuid): JsonResponse
    {
        $vessel = Vessel::where('uuid', $uuid)->first();

        if (! $vessel) {
            return $this->notFound('Vessel not found');
        }

        $vessel->update($request->validated());

        return $this->success(new VesselResource($vessel->fresh()), 'Vessel updated successfully');
    }

    /**
     * GET /api/v1/vessels/export
     */
    public function exportVessels(Request $request): JsonResponse
    {
        $vessels = Vessel::query()
            ->when($request->input('carrier_scac'), fn($q, $v) => $q->where('carrier_scac', $v))
            ->orderBy('eta', 'asc')
            ->get();

        return $this->success([
            'vessels'    => VesselResource::collection($vessels),
            'total'      => $vessels->count(),
            'export_url' => null, // Would be generated by export job in production
        ]);
    }

    /**
     * GET /api/v1/vessels/{uuid}/schedule
     */
    public function schedule(string $uuid): JsonResponse
    {
        $vessel = Vessel::where('uuid', $uuid)->first();

        if (! $vessel) {
            return $this->notFound('Vessel not found');
        }

        $schedule = $vessel->portCalls()
            ->orderBy('eta', 'asc')
            ->get()
            ->map(function ($call) {
                return [
                    'port_code'     => $call->port_code,
                    'port_name'     => $call->port_name,
                    'eta'           => $call->eta,
                    'etd'           => $call->etd,
                    'ata'           => $call->ata,
                    'atd'           => $call->atd,
                    'terminal_code' => $call->terminal_code,
                ];
            });

        return $this->success([
            'vessel'   => new VesselResource($vessel),
            'schedule' => $schedule,
        ]);
    }

    /**
     * GET /api/v1/vessels/{uuid}/containers
     */
    public function containers(string $uuid, Request $request): JsonResponse
    {
        $vessel = Vessel::where('uuid', $uuid)->first();

        if (! $vessel) {
            return $this->notFound('Vessel not found');
        }

        $query = $vessel->containers()->getQuery();

        $this->applySorting(
            $query,
            $request->input('order_by', 'container_number'),
            (int) $request->input('direction', 1)
        );

        return $this->paginateResource($query, $request, ContainerResource::class);
    }
}
